title: Hello, world! I'm Quoc DEV
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://quoc-dev.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "quocdev" #if your site has a twitter account, enter it here

# Author Settings
author: Quoc DEV # add your name
author-img: my_avatar.jpg # add your photo
about-author: I am a Android developer focusing on development. Always hungry to keep learning. # add description
twitter: quocdev # add your Twitter handle
facebook: quocdev # add your Facebook handle
github: quoc-dev # add your Github handle
linkedin: quocdev # add your Linkedin handle
email: phucquoc.dev@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
